package Models;

import DB.DatabaseController;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Date;

@Entity
public class Event {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id; //id is generated by the DB (do not set it)

    private String name;
    private String description;
    private String image;

    //if the timeline uses one of the time presets
    private LocalDateTime startDate;
    private LocalDateTime endDate;

    //if the timeline uses a custom time unit
    private LocalTime startInt;
    private LocalTime endInt;

    //private int timelineID;
    //if of the timeline where the event is in
    @ManyToOne
    @JoinColumn(name = "timeline_id")
    private Timeline timeline;

    //userID that created this event
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User createdBy;

    @Generated(GenerationTime.INSERT)
    private Date creationDate;


    public Event() {}

    public Event(String name, String description, String image, LocalDateTime startDate, LocalDateTime endDate, LocalTime start, LocalTime end, Timeline timeline, User createdBy) {
        this.name = name;
        this.description = description;
        this.image = image;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startInt = start;
        this.endInt = end;
        this.timeline = timeline;
        this.createdBy = createdBy;
    }

    public void editEvent(String name, String description, String image, LocalDateTime startDate, LocalDateTime endDate, LocalTime start, LocalTime end, Timeline timeline, User createdBy) {
        this.name = name;
        this.description = description;
        this.image = image;
        this.startDate = startDate;
        this.endDate = endDate;
        this.startInt = start;
        this.endInt = end;
        this.timeline = timeline;
        this.createdBy = createdBy;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        if (name.isEmpty()){
            throw new IllegalArgumentException("Name can not be Empty, Please enter a name for event");
        }
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public LocalDateTime getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    public LocalDateTime getEndDate() {
        return endDate;
    }

    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

    public LocalTime getStart() {
        return startInt;
    }

    public void setStart(LocalTime start) {
        this.startInt = start;
    }

    public LocalTime getEnd() {
        return endInt;
    }

    public void setEnd(LocalTime end) {
        this.endInt = end;
    }

    public Timeline getTimeline() {
        return timeline;
    }

    public void setTimeline(Timeline timeline) {
        this.timeline = timeline;
    }

    public User getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(User createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date createdAt) {
        this.creationDate = createdAt;
    }


    //DB CRUD
    public void save() {
        DatabaseController.createRecord(this);
    }

    public void update() {
        DatabaseController.updateRecord(this);
    }

    public void delete() {
        DatabaseController.deleteRecord(this.id, Event.class);
    }

    static public Event load(int id) {
        return (Event) DatabaseController.getRecord(id, Event.class);
    }
}