package Models;

import DB.Database;
import DB.DatabaseController;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

import javax.persistence.*;
import java.util.Date;
import java.util.List;

@Entity
//@Table(name = "User")
public class User {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @Column(name = "id")
    private int id; //id is generated by the DB (do not set it)

//    @Column(name = "username")
    private String username;

//    @Column(name = "fullname")
    private String fullname;

//    @Column(name = "password")
    private String password;

//    @Column(name = "passwordHint")
    private String passwordHint;

//    @Column(name = "image")
    private String image;

//    @Column(name = "isAdmin")
    private boolean isAdmin;

    @Generated(GenerationTime.INSERT)
    private Date creationDate; //creationDate is generated by the DB (do not set it)

    private List<Timeline> timelines;


    public User() {};

    public User(String username, String fullname, String password, String passwordHint, String image, boolean isAdmin) {
        this.username = username;
        this.fullname = fullname;
        this.password = password;
        this.passwordHint = passwordHint;
        this.image = image;
        this.isAdmin = isAdmin;
    }

    public void editUser(String username, String fullname, String password, String passwordHint, String image, boolean isAdmin) {
        this.username = username;
        this.fullname = fullname;
        this.password = password;
        this.passwordHint = passwordHint;
        this.image = image;
        this.isAdmin = isAdmin;
    }

    //For test purposes only
    public static User getTestUser() {
        return new User("John Snow", "", null, "shadowhunter2000", "ala", false);
    }


    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String text) {
        this.username = text;
    }

    public String getFullname() {
        return fullname;
    }

    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    public String getPassword(){return this.password;}

    public void setPassword(String password) {
        this.password = password;
    }

    public String getPasswordHint() {
        return passwordHint;
    }

    public void setPasswordHint(String text) {
        this.passwordHint = text;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String text) {
        this.image = image;
    }

    public boolean isAdmin() {
        return isAdmin;
    }

    public void setAdmin(boolean admin) {
        isAdmin = admin;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public List<Timeline> getTimelines() {
        return timelines;
    }

    public void setTimelines(List<Timeline> timelines) {
        this.timelines = timelines;
    }

    //DB CRUD
    public void save() {
        DatabaseController.createRecord(this);
    }

    public void update() {
        DatabaseController.updateRecord(this);
    }

    public void delete() {
        DatabaseController.deleteRecord(this.id, User.class);
    }

    static public User load(int id) {
        return (User) DatabaseController.getRecord(id, User.class);
    }

    //DB get by username and password
    public static User login(String username, String password) {
        return DatabaseController.getUserByUsernamePassword(username,password);
    }
}


